ARG TESTSUITE_TOMCAT_VERSION=10.1

FROM tomcat:${TESTSUITE_TOMCAT_VERSION}

ARG TESTSUITE_TOMCAT_VERSION
ARG TESTSUITE_TOMCAT_CONFIG=server.xml
ARG TESTSUITE_TOMCAT_CONTEXT=context.xml

# install ss
RUN apt-get update && apt-get install -y iproute2 unzip

COPY target/mod_cluster-distribution-*-tomcat-${TESTSUITE_TOMCAT_VERSION}.zip /tmp/
RUN unzip /tmp/mod_cluster-distribution-*-tomcat-${TESTSUITE_TOMCAT_VERSION}.zip && \
    cp mod_cluster-distribution-*/lib/*.jar /usr/local/tomcat/lib/

COPY $TESTSUITE_TOMCAT_CONFIG  ./conf/server.xml
COPY $TESTSUITE_TOMCAT_CONTEXT ./conf/context.xml
COPY --chmod=755 start.sh ./

ENV cluster_port=8090
ENV cluster_address=127.0.0.1
ENV jvm_route=
ENV tomcat_address=
ENV tomcat_port_offset=0

CMD ["./start.sh"]

