ARG TESTSUITE_TOMCAT_VERSION=10.1

FROM tomcat:${TESTSUITE_TOMCAT_VERSION}

ARG TESTSUITE_TOMCAT_VERSION
ARG TESTSUITE_TOMCAT_CONFIG=server.xml
ARG TESTSUITE_TOMCAT_CONTEXT=context.xml

# install ss
RUN apt-get update && apt-get install -y iproute2 unzip

COPY target/mod_cluster-distribution-*-tomcat-${TESTSUITE_TOMCAT_VERSION}.zip /tmp/
RUN unzip /tmp/mod_cluster-distribution-*-tomcat-${TESTSUITE_TOMCAT_VERSION}.zip && \
    cp mod_cluster-distribution-*/lib/*.jar /usr/local/tomcat/lib/

COPY $TESTSUITE_TOMCAT_CONFIG ./conf/server.xml
COPY --chmod=755 start.sh ./

ENV proxy_port=8090
ENV proxy_address=httpd-mod_proxy_cluster
ENV jvm_route=
ENV tomcat_address=localhost
ENV tomcat_port=8080
ENV tomcat_shutdown_port=8005
ENV tomcat_ajp_port=8900
ENV tomcat_port_offset=0

CMD ["./start.sh"]
