ARG TESTSUITE_TOMCAT_VERSION=10.1

FROM tomcat:${TESTSUITE_TOMCAT_VERSION}

ARG TESTSUITE_TOMCAT_CONFIG=server.xml
ARG TESTSUITE_TOMCAT_CONTEXT=context.xml

# install ss
RUN apt-get update && apt-get install -y iproute2

WORKDIR /usr/local/tomcat

COPY target/*.jar ./lib/

COPY $TESTSUITE_TOMCAT_CONFIG  ./conf/server.xml
COPY $TESTSUITE_TOMCAT_CONTEXT ./conf/context.xml
COPY --chmod=755 start.sh ./

ENV cluster_port=8000
ENV cluster_address=127.0.0.1
ENV jvm_route=
ENV tomcat_address=
ENV tomcat_port_offset=0

CMD ["./start.sh"]

