#!/bin/sh

#
# Copyright The mod_cluster Project Authors
# SPDX-License-Identifier: Apache-2.0
#

rm -rf aclocal.m4 autom4te*.cache

echo "Creating configure ..."
### do some work to toss config.cache?
if ${AUTOCONF:-autoconf}; then
  :
else
  echo "autoconf failed"
  exit 1
fi
