FROM fedora:41 AS builder

ARG HTTPD_SOURCES="https://dlcdn.apache.org/httpd/httpd-2.4.65.tar.gz"

RUN dnf install gcc apr-devel apr-util-devel openssl-devel pcre-devel redhat-rpm-config autoconf wcstools -y

ENV CONF=httpd/mod_proxy_cluster.conf
ENV HTTPD=${HTTPD_SOURCES}

# make sure you have copy of the local repository at place
# (our function "httpd_create" takes care of that)
COPY mod_proxy_cluster /

ADD ${HTTPD} .

RUN mkdir /httpd && tar xvf $(filename $HTTPD) --strip 1 -C /httpd

WORKDIR /httpd

RUN ./configure --enable-proxy \
                --enable-proxy-http \
                --enable-proxy-ajp \
                --enable-proxy-wstunnel \
                --enable-proxy-hcheck \
                --with-port=8000
RUN make
RUN make install

# httpd is installed in /usr/local/apache2/bin/
# build and install mod_proxy_cluster *.so files.
WORKDIR /native
RUN for m in advertise mod_proxy_cluster balancers mod_manager; \
    do \
        cd $m; \
        echo "Building $m"; \
        ./buildconf; \
        ./configure --with-apxs=/usr/local/apache2/bin/apxs; \
        make clean; \
        make || exit 1; \
        cp *.so /usr/local/apache2/modules; \
        cd $OLDPWD; \
    done;

RUN rm -rf /test/httpd/mod_proxy_cluster

FROM fedora:41

RUN dnf install pcre apr-util wcstools -y

COPY --from=builder /usr/local/apache2 /usr/local/apache2

COPY --from=builder /test /test

COPY run.sh /tmp

WORKDIR /usr/local/apache2

CMD /tmp/run.sh
