FROM fedora:44 AS builder

ARG HTTPD_SOURCES="https://dlcdn.apache.org/httpd/httpd-2.4.69.tar.gz"
ARG ENABLE_COVERAGE=""

RUN dnf install gcc apr-devel apr-util-devel openssl-devel pcre-devel redhat-rpm-config wcstools cmake -y

ENV HTTPD=${HTTPD_SOURCES}

# make sure you have copy of the local repository at place
# (our function "httpd_create" takes care of that)
COPY mod_proxy_cluster /

ADD ${HTTPD} .

RUN mkdir /httpd && tar xvf $(filename $HTTPD) --strip 1 -C /httpd

WORKDIR /httpd

RUN ./configure --enable-proxy \
                --enable-proxy-http \
                --enable-proxy-ajp \
                --enable-proxy-wstunnel \
                --enable-proxy-hcheck
RUN make
RUN make install
# we don't need any other listeners except the ones we define in our config files
RUN sed -i 's/\(Listen 80\)/#\1/' /usr/local/apache2/conf/httpd.conf

# httpd is installed in /usr/local/apache2/bin/
# build and install mod_proxy_cluster *.so files.
WORKDIR /native

RUN mkdir build || true

RUN cd build && rm -rf * && cmake .. -DAPACHE_INCLUDE_DIR=/usr/local/apache2/include -DENABLE_COVERAGE=${ENABLE_COVERAGE:-OFF} && make && for f in modules/*.so; do ln -s "$PWD/$f" /usr/local/apache2/$f; done;

RUN rm -rf /test/httpd/mod_proxy_cluster

FROM fedora:44

ENV CONF=httpd/mod_proxy_cluster.conf

RUN dnf install pcre apr-util wcstools gcc gcovr lcov -y

COPY --from=builder /usr/local/apache2 /usr/local/apache2
COPY --from=builder /native /native

COPY --from=builder /test /test

COPY run.sh /tmp

WORKDIR /usr/local/apache2

CMD /tmp/run.sh
