name: Skip CI on ignored paths
on:
  push:
    paths:
      - '.gitignore'
      - '**.md'
      - 'LICENSE'
  pull_request:
    paths:
      - '.gitignore'
      - '**.md'
      - 'LICENSE'

jobs:

  gather-results:
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "Skipping the job"

